web/modules/custom/events_manager/src/Form/EventDeleteForm.php
<?php
	/**
	 * @file
	 * @Contains Drupal\events_manager\Form\EventDeleteForm.
	 */
	namespace Drupal\events_manager\Form;

	use Drupal\Core\Form\FormStateInterface;
	use Drupal\Core\Form\ConfirmFormBase;
	use Drupal\Core\Url;

	/**
	 * Class EventDeleteForm
	 * @package Drupal\events_manager\Form
	 */
	class EventDeleteForm extends ConfirmFormBase {
		public $event;

		/**
		 * {@inheritdoc}
		 */
		public function getFormId() {
			return 'delete_form';
		}

		public function getQuestion() {
			return $this->t('Delete data');
		}

		public function getCancelUrl() {
			return new Url('event.list');
		}

		public function getDescription() {
			return $this->t('Do you want to delete data number %event ?', ['%event' => $this->event]);
		}

		/**
		 * {@inheritdoc}
		 */
		public function getConfirmText() {
			return $this->t('Delete it!');
		}

		/**
		 * {@inheritdoc}
		 */
		public function getCancelText() {
			return $this->t('Cancel');
		}

		/**
		 * {@inheritdoc}
		 */
		public function buildForm(array $form, FormStateInterface $form_state, $event = NULL) {

			$this->event = $event;
			return parent::buildForm($form, $form_state);
		}

		/**
		 * {@inheritdoc}
		 */
		public function validateForm(array &$form, FormStateInterface $form_state) {
			parent::validateForm($form, $form_state);
		}

		/**
		 * {@inheritdoc}
		 */
		public function submitForm(array &$form, FormStateInterface $form_state) {
			$query = \Drupal::database();
			$query->delete('events')
				->condition('id', $this->event)
				->execute();
			\Drupal::messenger()->addStatus('Successfully deleted.');
			$form_state->setRedirect('event.list');
		}
	}

web/modules/custom/events_manager/templates/events-manager-event-list.html.twig
<div class="mb-3">
    <a href="{{ add_event_url }}" class="button button--primary">
        + Create Event
    </a>
</div>
<table class="table table-striped">
    <thead>
    <tr>
        <th>IDs</th>
        <th>Title</th>
        <th>Image</th>
        <th>Description</th>
        <th>Start</th>
        <th>End</th>
        <th>Category</th>
        <th>Actions</th>
    </tr>
    </thead>
    <tbody>
    {% for event in events %}
        <tr>
            <td>{{ event.id }}</td>
            <td>{{ event.title }} </td>
            <td><img src="{{ event.image }}" alt="{{ event.title }}" width="60" /></td>
            <td>{{ event.description }}</td>
            <td>{{ event.start_time }}</td>
            <td>{{ event.end_time }}</td>
            <td>{{ event.category }}</td>
            <td>
                {{ event.view }}
                {{ event.edit }}
                {{ event.delete }}
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>

    {{ pager }}